#!/usr/bin/env node

/**
 * Generate Summary Report Script
 * 
 * Creates a markdown summary report of the autofix process
 */

const fs = require('fs');
const path = require('path');

const ANALYSIS_FILE = 'scripts/pr-autofix/review-analysis.json';
const FIX_PLAN_FILE = 'scripts/pr-autofix/fix-plan.json';
const OUTPUT_FILE = 'scripts/pr-autofix/SUMMARY.md';

/**
 * Main function
 */
function main() {
  console.log('=== Generate Summary Report ===\n');
  
  try {
    // Read analysis
    const hasAnalysis = fs.existsSync(ANALYSIS_FILE);
    const hasFixPlan = fs.existsSync(FIX_PLAN_FILE);
    
    let analysis = null;
    let fixPlan = null;
    
    if (hasAnalysis) {
      analysis = JSON.parse(fs.readFileSync(ANALYSIS_FILE, 'utf-8'));
    }
    
    if (hasFixPlan) {
      fixPlan = JSON.parse(fs.readFileSync(FIX_PLAN_FILE, 'utf-8'));
    }
    
    // Generate report
    const report = generateReport(analysis, fixPlan);
    
    // Write report
    fs.writeFileSync(OUTPUT_FILE, report);
    
    console.log(`Report generated: ${OUTPUT_FILE}`);
    console.log('\n✅ Report generated successfully!');
    
  } catch (error) {
    console.error('Error generating report:', error);
    process.exit(1);
  }
}

/**
 * Generate markdown report
 */
function generateReport(analysis, fixPlan) {
  let report = '# PR Auto-Fix Summary Report\n\n';
  report += `Generated: ${new Date().toISOString()}\n\n`;
  
  // Overview section
  report += '## Overview\n\n';
  
  if (analysis) {
    report += `- **PR Number:** #${analysis.prNumber}\n`;
    report += `- **Total Comments Analyzed:** ${analysis.totalComments}\n`;
    report += `- **Issues Found:** ${analysis.parsedComments.length}\n`;
  } else {
    report += '- **Analysis:** Not available\n';
  }
  
  // Summary section
  if (analysis && analysis.summary) {
    report += '\n### Summary by Tool\n\n';
    for (const [tool, count] of Object.entries(analysis.summary.byTool)) {
      report += `- ${tool}: ${count}\n`;
    }
    
    report += '\n### Summary by Type\n\n';
    for (const [type, count] of Object.entries(analysis.summary.byType)) {
      report += `- ${type}: ${count}\n`;
    }
    
    report += '\n### Summary by Priority\n\n';
    for (const [priority, count] of Object.entries(analysis.summary.byPriority)) {
      report += `- ${priority}: ${count}\n`;
    }
  }
  
  // Recommendations section
  if (analysis && analysis.recommendations) {
    report += '\n## Recommendations\n\n';
    for (const rec of analysis.recommendations) {
      report += `- ${rec}\n`;
    }
  }
  
  // Fix Plan section
  if (fixPlan) {
    report += '\n## Fix Plan\n\n';
    report += `- **Total Fixes:** ${fixPlan.totalItems}\n`;
    report += `- **Parallel Files:** ${fixPlan.parallelFiles.length}\n`;
    report += `- **Sequential (Before):** ${fixPlan.sequentialFiles.before.length}\n`;
    report += `- **Sequential (After):** ${fixPlan.sequentialFiles.after.length}\n`;
    
    if (fixPlan.parallelFiles.length > 0) {
      report += '\n### Files to Fix in Parallel\n\n';
      for (const file of fixPlan.parallelFiles) {
        report += `- \`${file}\`\n`;
      }
    }
    
    if (fixPlan.sequentialFiles.before.length > 0) {
      report += '\n### Critical/Security Fixes (Sequential - Before)\n\n';
      for (const file of fixPlan.sequentialFiles.before) {
        report += `- \`${file}\`\n`;
      }
    }
    
    if (fixPlan.sequentialFiles.after.length > 0) {
      report += '\n### Low Priority Fixes (Sequential - After)\n\n';
      for (const file of fixPlan.sequentialFiles.after) {
        report += `- \`${file}\`\n`;
      }
    }
    
    // Fix items
    if (fixPlan.items && fixPlan.items.length > 0) {
      report += '\n## Detailed Fixes\n\n';
      
      for (const item of fixPlan.items) {
        report += `### \`${item.file}\`\n\n`;
        report += `- **Type:** ${item.type}\n`;
        report += `- **Priority:** ${item.priority}\n`;
        report += `- **Tool:** ${item.tool}\n`;
        report += `- **Line:** ${item.line || 'N/A'}\n`;
        if (item.suggestion) {
          report += `- **Suggestion:** \`${item.suggestion.substring(0, 100)}\`\n`;
        }
        report += '\n---\n\n';
      }
    }
  }
  
  // Footer
  report += '\n---\n';
  report += '_Generated by @kilo-autofix_\n';
  
  return report;
}

main();
